config/routes.rb
Rails.application.routes.draw do
  #Create one task
  get 'tasks/new', to: 'tasks#new', as: :newtask
  post 'tasks', to: 'tasks#create'
  #Read all taks
  get 'tasks', to: 'tasks#index'
  #Read one task
  get 'tasks/:id', to: 'tasks#show', as: :task
  #Update one tak
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  #Delete one task
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroytask
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @task.save
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= form_for @task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>

  <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<h1>Task Manager</h1>

<p id="btn-add"><%= link_to "Add a post", newtask_path %></p>

<ul>
  <% @tasks.each do |task| %>
  <li><%= task.completed %>
      <%= link_to task.title, task_path(task) %>
      <%= task.details %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>

<%= form_for @task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>

  <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= link_to "Edit", edit_path %></p>

<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<p><%= link_to "Delete", destroytask_path %></p>

<p><%= link_to "Back to list", tasks_path %></p>